version: '3'

services:
  app:
    build: .
    command: npm start
    ports:
      - '8007:8007'
    volumes:
      - .:/usr/app
    networks:
      - backend

networks:
  backend:
    driver: bridge
